services:
  rag_app:
    build:
      context: .
    container_name: streamlit_rag_app
    network_mode: "host" 
    volumes:
      - ./src:/app/src
      - ./vectorstores:/app/vectorstores
      - ./PHCheng.pem:/app/PHCheng.pem
    environment:
      - OLLAMA_URL=http://127.0.0.1:11434